### PR TITLE
Sort keys in preview of `featureHtml`

### PR DESCRIPTION
**Pull request by tordans**
With this, every Popup shows the keys in the same order.

Just something small to make debugging the data easiert.

### CODE REVIEW

**Comment by pramsey** [comment]
The holy grail is actually sorting them in table order... :)

**Comment by pramsey** [comment]
Actually I really mean it, alphabetizing the keys can be more confusing than the alternative (well, maybe not more confusing than random, so table-order is the desired enhancement here.

**Comment by tordans** [comment]
I still don't get it. Right now it is random … which is more confusing that A-Z (as you stated as well). 

Also, A-Z is a quick win, where sort by sql-table-order … I would not even know where to start and think that it is not even possible given that some data comes from jsonb fields.

**Comment by pramsey** [comment]
OK, I can buy that the perfect is the enemy of the good. Still would love a table order PR....

**Pull request merged**
