### PR TITLE
Basic Prometheus metrics

### PR DESCRIPTION
**Pull request by stephenhillier**
Here are some basic Prometheus metrics (for #94). If interested I can make a similar PR for pg_featureserv.

Metrics can be enabled using a new `EnableMetrics` config option.

This includes a counter and a histogram, which is enough to let you graph the tile request rate (e.g. tiles generated per second/minute/hour etc.), error rate, and response times. There's a label for the layer name so you can group everything that way.

I can add better tests but it would require #5 in order to make test calls to a layer endpoint.

### CODE REVIEW

**Comment by stephenhillier** [comment]
I'd like to make sure the metrics only capture valid layers (to prevent somebody making unlimited labels on the server by intentionally generating a bunch of 404's), but the server returns 500 instead of 404 if a layer isn't found.  I'll come up with a solution. Any objections if I change the error code to 404 in that case?

**Comment by pramsey** [comment]
Go ahead and change the error code.

**Comment by stephenhillier** [comment]
I added 404 and 400 errors. 404 for when a layer is not found, 400 for an invalid tile z/x/y (I checked OSM and basemaps.cartocdn.com and this is what they both return). The metrics will ignore requests that return these kinds of errors but 500 errors will still be tracked so that server error rates can be monitored.

**Comment by pramsey** [comment]
Is this mergeable now?

**Comment by stephenhillier** [comment]
Yes, the metrics are opt-in with the `EnableMetrics` config option, if that's ok with you then it's ready.

**Pull request merged**
