### PR TITLE
Dependency updates

### PR DESCRIPTION
**Pull request by eldang**
A client's software QA process flagged some indirect dependencies as having vulnerabilities of concern.  This is my attempt to deal with all of those.  Along the way I also made some fixes to the test suite so I could run it with each dependency update.  I have also tested this on my localhost and it's working indistinguishably from before the updates.

### CODE REVIEW

**Comment by eldang** [comment]
CI fail noted.  I'm running Go 1.21.4 locally and hadn't anticipated that this would be an issue.  I'm going to see if just updating the required version in `go.mod` to 1.18 is sufficient.  If not, then I'll close this PR and reconsider my approach.

Meanwhile, @pramsey do you have an opinion about minimum Go versions to support?

**Comment by pramsey** [comment]
I honestly don't! I have no feel for the tradeoffs involved. You?

**Comment by eldang** [comment]
> I honestly don't! I have no feel for the tradeoffs involved. You?

It's not really something I know enough about either.  I generally have a preference for latest stable versions because of things like this SQA audit I've run into, but I don't have a good sense of how many people (if any) that would cause problems for because they're stuck with an older version in their environment.

**Comment by eldang** [comment]
Meanwhile, my attempts at obvious fixes are failing and I don't want to get sucked too deep into debugging a dependency.  So I'm closing this PR for now; will open a new one if I figure it out.

**Pull request closed without merging**
