### PR TITLE
Basic HTTPS and HTTP/2 support

### LINKED ISSUE #7: SSL configuration options and documentation

### PR DESCRIPTION
**Pull request by s8mathur**
Fixes #7.
- Add configuration parameters to allow call to `ListenAndServeTLS`
- Verified that HTTP/2 works when connecting to `pg_tileserv` in TLS mode via CaddyServer (`proxy` mode with `insecureskipverify` to the default HTTPS port 7801) and using `curl -k` .
- HTTP/2 request multiplexing should now work helping with tile delivery throughput in production setups

### CODE REVIEW

**Comment by pramsey** [comment]
Thanks, looks good. I don't see HTTP/2 changes mentioned in comment?

**Comment by s8mathur** [comment]
> Thanks, looks good. I don't see HTTP/2 changes mentioned in comment?

HTTP/2 works automagically with Go's out-of-the-box HTTPS support. Easily verifiable by making a request `curl -v` to the endpoint.

**Comment by dr-jts** [comment]
Would be good to add this to README.

**Comment by dr-jts** [comment]
Would be nice to not advertise (in startup log) that HTTPS is being served if the cert params have not been configured.

**Comment by dr-jts** [comment]
Perhaps worth noting how to generate a cert for development purposes.  Does this work?
```
openssl req -newkey rsa:2048 -new -nodes -x509 -days 3650 -keyout key.pem -out cert.pem
```

**Comment by dr-jts** [comment]
It looks to me like the preview is requesting tiles with `http` even when loaded with an `https` request.  So perhaps this is a bug?

**Pull request merged**
