### PR TITLE
docs: a better polyfill for st_tileenvelope

### PR DESCRIPTION
**Pull request by jingsam**
A better st_tileenvelope that supports `bounds` and `margin`

### CODE REVIEW

**Comment by pramsey** [comment]
What makes it better, in your opinion?

**Comment by jingsam** [comment]
> What makes it better, in your opinion?

This `st_tileenvelope` is more compliant to the functionality in PostGIS 3.0. As bellow:
1、Supports any coordinate system, not just EPSG:3857.
2、Supports custom bounds, not only [-20037508.3427892, -20037508.3427892, 20037508.3427892, 20037508.3427892].
3、Supports `margin` parameter to specify a buffer.

**Comment by pramsey** [comment]
Do you think the extra complexity is warranted in an example function? It
makes it a harder read, IMO. I guess most people just copy / paste it. In
the same vein though most people are now 3.0+ anyways so it's probably
little used?

**Comment by jingsam** [comment]
> In the same vein though most people are now 3.0+ anyways so it's probably little used?

I use Greenplump a lot, it is integrated with PostGIS 2.5.4. And Also we use pg_tileserv to generate vector tiles with EPSG:4326. That's why I need a more compatible `st_tileenevnlope` function. If you think my use case is niche, just close this PR. I am OK with it.

**Comment by pramsey** [comment]
I think I'd rather move towards not having the polyfill in the docs as 2.x recedes into history rather than making it more and better. Thanks for the submission nonetheless!

**Pull request closed without merging**
