### PR TITLE
Fix for non-mercator tiles

### PR DESCRIPTION
**Pull request by jomue**
I've tried to generate tiles in EPSG:25832 (ETRS89 / UTM zone 32N), but encountered only empty tiles. This PR fixes this problem.

#### My testdata
Danish municipalities in EPSG:25832

#### My configuration
```
[CoordinateSystem]
SRID = 25832
Xmin = 120000.0
Ymin = 5661139.2
Xmax = 958860.8
Ymax = 6500000.0
```

#### What did I test?
- Generating tiles in EPSG:25832
- Generating tiles in EPSG:3857

#### Result
image

How do you feel about this change?

### CODE REVIEW

**Comment by pramsey** [comment]
Wonderful, I knew I was missing something obvious. Do you have a references to that non-mercator tile service you are using for a base? Would be helpful for demos.

**Comment by jomue** [comment]
I'm using data from the danish Agency for Datasupply and Efficiency, which is freely available at [Kortforsyningen](https://kortforsyningen.dk/indhold/english). But it is necessary to register a user there in order to get a token for the WMS. This is also where I got the municipalitiy shape file from.

Alternatively, you could take a look at the [OpenStreetMap WMS provided by terrestris](https://www.terrestris.de/en/openstreetmap-wms/), which is available in EPSG:25832 and other projections.

**Comment by pramsey** [comment]
What web map code did you use to build that overlay? I'm fighting with openlayers right now. Could you drop an example here?

**Comment by jomue** [comment]
I've adapted an OpenLayers example for you: https://codesandbox.io/s/goofy-lewin-uzs5j?file=/main.js
Hope that helps 😃

**Comment by pramsey** [comment]
Ug, yes and no. Where does that list of resolutions come from? In my heart of hearts, I was hoping supporting a non-standard projection would be as simple as saying "here are the square bounds of my zoom 0 tile". But this seems a lot harder. Is this magic explained anywhere in documentation?

**Comment by jomue** [comment]
Ah, sorry to disappoint you. I've been trying to match the resolution and bounds that are documented for the most common WMTS services in Denmark: https://kortforsyningen.dk/content/wmts#TileMatrixSet

Note that I had to add 3276.8 to the resolutions to get data to show up correctly. Unfortunately, I don't know why this was necessary though.

I've previously used t-rex to generate vector tiles, which expects bounds and resolutions when defining a custom tile grid (https://t-rex.tileserver.ch/doc/reference/). This might feel a bit less like magic, but complicates the configuration.

**Comment by pramsey** [comment]
I wonder if @Bartvde has any thoughts on simple-looking ways to configure openlayers for non-3857 vector tiles

**Comment by bartvde** [comment]
I'm really out of touch with openlayers these days, but I'm sure @ahocevar knows

**Comment by ahocevar** [comment]
@pramsey For sure: https://codesandbox.io/s/wonderful-northcutt-fkv24?file=/main.js. @jomue's [configuration](https://github.com/CrunchyData/pg_tileserv/pull/61#issue-519201104) translates to the following projection definition:
```js
var projection = new Projection({
  code: "EPSG:25832",
  units: "m",
  extent: [120000, 5661139.2, 958860.8, 6500000]
});
```
Now all you have to do is set that projection on your vector tile source, and on the view. If the vector tile set uses a different tile size than 512, you also have to set the `tileSize` on the vector tile source. So assuming the tile size is the default of 512, your vector tile layer definition will look like this:
```js
var vtLayer = new VectorTileLayer({
  source: new VectorTile({
    format: new MVT(),
    projection: projection,
    url: "http://path/to/my/vector_tiles/{z}/{x}/{y}.pbf"
  })
});
```
That's it. In the codesandbox above I also added a layer that shows the tile grid the vtLayer uses for debugging purposes:
```js
new TileLayer({
  source: new TileDebug({
    projection: projection,
    tileGrid: vtLayer.getSource().getTileGrid(),
    zDirection: 1
  })
})
```
I hope this helps.

**Comment by pramsey** [comment]
This seems close to many things I tried, but I will try again and see if getting just the right incantation does the trick! Thanks!

**Comment by pramsey** [comment]
Well, that worked perfectly, which is a little frustrating, since I tried so many very similar things. One projection object at the top, with an extent, and used in the layers, and map, no other references to projection or extent, and Magic Happens

**Pull request merged**
